### ISSUE TITLE
Should auto abort after successfully fetch

### ISSUE THREAD

**Issue by alt1o** [joshmossas/event-source-plus#19]
**Environment**

Browser

**Reproduction**

```
const eventSource = new EventSourcePlus(url)

eventSource.listen({
  onMessage(message) {
     console.log('message', message);
  }
})
```

**Describe the bug**

After successfully fetching, I don't call abort manually, so it continues to retry. After debug, it seems I should call abort manually, otherwise, signal.aborted will always be false.

![image](https://github.com/user-attachments/assets/b7426246-0220-43e8-b082-91ad0ec59b18)

<img width="547" alt="image" src="https://github.com/user-attachments/assets/d15be8bb-f6c6-41ac-9e64-29ccbfa947e8">

**Comment by joshmossas** [comment]
Hello @alt1o 

Continually reconnecting is pretty standard behavior for SSE clients. For example if you use the built-in `EventSource` class in Chrome the client infinitely reconnects unless manually closed. (Do note that this does vary from browser to browser.)

A connection has to remain open in order to facilitate this pushing events from the server to the client. So it makes sense that the client would do work to make sure a connection always stays open.

In my experience, the way that people signal that an even stream has ended is that people will send a "done" or "finished" event. Then on the client side they will watch for those events to know that they should close the connection.

Example:

The client may watch for an event like this and close the connection upon receipt.
```txt
event: finished
data: No more events

```

**Comment by joshmossas** [comment]
![image](https://github.com/user-attachments/assets/066f4a7d-ba30-45ab-a59f-8439186fb16d)

Another example. Here is how ChatGPT is streaming responses to the client. the `[DONE]` message is used to notify the client that the connection should be closed. So you would call `abort()` upon receiving that message.

I might be open to adding an option that doesn't auto-reconnect if the request completed successfully. I'll have to think about what that would look like. It would be non-standard, but if it's disabled by default then it might be okay.

**Comment by alt1o** [comment]
It's so nice of you to tell me the background in detail. Actually, I'm writing an LLM app using API. I just use chat API in stream mode, so I don't want to integrate OpenAPI Client. In OpenAPI Client, they only retry when `response.ok` is false or a response instance of Error. Maybe an option for modifying the retry strategy is better.

https://github.com/openai/openai-node/blob/master/src/core.ts#L470
![image](https://github.com/user-attachments/assets/add37e92-4c87-474b-9398-394f65c7a1fe)

**Comment by joshmossas** [comment]
Hmm yeah the more I think about it the more I think adding an option for adjusting the retry strategy would be good. It'll prolly especially be useful for LLM apps since you won't have to listen for a "done" event.

Maybe it can look something like this:

```ts
type RetryStrategy = "ALWAYS" | "ON_ERROR" // `ALWAYS` is default
```

And then using it would look something like this:

```ts
const eventSource = new EventSourcePlus(url, { retryStrategy: "ON_ERROR" });
```

IDK. What do you think @alt1o?

**Comment by joshmossas** [comment]
Hey @alt1o 

I've gone ahead and merged a change that allows you to change the retry strategy. It will be live in `v0.1.8` marked as a BETA feature. See https://github.com/joshmossas/event-source-plus/pull/21

Documentation can be found [here](https://github.com/joshmossas/event-source-plus?tab=readme-ov-file#changing-the-retry-strategy-beta)

Please let me know what you think and if it ends up working for your use cases. I'll probably keep it marked as a beta for a bit just to make sure there aren't any unaccounted for edge cases.
