### ISSUE TITLE
retry on Server dropping the connection

### ISSUE THREAD

**Issue by leoVetterli** [joshmossas/event-source-plus#24]
If the server closes the connection (no error), event-source-plus will try to reconnect.
Because you are resetting retryCount and intervall, the reconnection does not use those settings, tries indefinitely and at a very fast rate.

https://github.com/joshmossas/event-source-plus/blob/85b693464be03b8e0838ee09f6ca7a67c982818e/src/event-source.ts#L122C1-L123C36

**Comment by joshmossas** [comment]
Hello @leoVetterli,

I recommend you change the retry strategy of the client. This will likely produce the behavior that you are looking for. 

```ts
const es = new EventSourcePlus("https://example.com/some-endpoint", {
  retryStrategy: "on-error",
})
```

See documentation on this feature [here](https://github.com/joshmossas/event-source-plus?tab=readme-ov-file#changing-the-retry-strategy-beta)

For further context as to why the library behaves the way it does by default, read below:

By default, we retry when the server drops the connection because this is the behavior of the built-in `EventSource` class in browsers. Server sent events were original created as a way to enable on-way realtime functionality for things like chat rooms and notifications. This kind of realtime functionality means that SSE clients have to keep an active connection open with the server, so it's only natural that it would try to reconnect if the connection gets dropped. This is also the reason retryInterval and retryCount are reset upon successful connection because those are mechanisms for handling error states.

However, in recent years server sent events have been used for streaming one off responses - particularly in LLM applications. Those kinds of applications don't benefit from always reconnecting since it's just a one off response. That is the reason I added the `retryStrategy` feature. It gives us the benefit of adhering closer to built-in browser implementations by default but also allows devs to switch to a more LLM friendly strategy if needed.
