### ISSUE TITLE
How to close the sse event

### ISSUE THREAD

**Issue by vishnug-bridge** [joshmossas/event-source-plus#8]
How do I close SSE when a user logout?

**Comment by joshmossas** [comment]
Hey @vishnug-bridge

Have you read through the documentation here on cancelling/aborting requests?
https://github.com/joshmossas/event-source-plus?tab=readme-ov-file#canceling-requests

Usually all you need to do is call `abort()` as outlined there in order to close SSE.

If that still doesn't give you the answer you need, could you provide more details concerning your authentication setup and how exactly you're trying to make it work with this library?
